require("plugins.init")
require("plugins.options")
require("plugins.keymaps")

require("configs.cmp")
require("configs.formatter")
require("configs.linter")
require("configs.lualine")
require("configs.mason")
require("configs.lspconfig")
require("configs.telescope")
require("configs.toggleterm")
require("configs.treesitter")
