require "user.options"
require "user.keymaps"
require "user.plugins"

require "plugins.neo-tree"
require "plugins.lualine"
require "plugins.gitsigns"
require "plugins.toggleterm"
require "plugins.telescope"
require "plugins.treesitter"
require "plugins.cmp"
require "plugins.mason"
require "plugins.rest-client"
require "plugins.guard"
