require "user.options"
require "user.keymaps"
require "user.plugins"

require "plugins.neotree"
require "plugins.lualine"
require "plugins.gitsigns"
require "plugins.toggleterm"
require "plugins.telescope"
require "plugins.treesitter"
require "plugins.cmp"
require "plugins.mason"
require "plugins.formatter"
